#!/usr/bin/env bash
# Copyright 2026 Hee-Suk Kim <hskim@dilluti0n.com>
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

. lib.bash

usage() {
    cat <<EOF
usage: ${NAME} [-t <refname>] <chain-ish>
       ${NAME} [-t <refname>] -f <ref>
       ${NAME} -h

Move HEAD to <chain-ish>. By default, HEAD is detached at the resolved
chain
  -t  save HEAD to <refname> before switch
  -f  HEAD follows <ref> after switch
  -h  print this help
EOF
}

symbolic= refname=
while getopts hft: o; do
    case $o in
        h) usage; exit 0 ;;
        f) symbolic=true ;;
        t) refname="$OPTARG" ;;
        *) usage; exit 1 ;;
    esac
done
shift $((OPTIND - 1))

[[ $# -eq 1 ]] || { usage >&2; exit 1; }
chain="$1"

[[ -n $refname ]] && sib save "$refname"

is_head_rev() {
    local b=${1%%[~^:]*}
    b=${b%%@\{*}
    case $b in
        HEAD|@|'') return 0 ;;
    esac
    return 1
}

# xxx, conv/xxx, refs/conv/xxx -> refs/conv/xxx
conv_ref() {
    local r=${1#refs/}
    printf 'refs/conv/%s\n' "${r#conv/}"
}

if [[ -n $symbolic ]]; then
    is_head_rev "$chain" && die "-f: $chain is not ref"
    target=$(conv_ref "$chain")
    sib symbolic-ref -m "switch to symbolic $chain" HEAD "$target" ||
        die "invalid name: $chain"
    echo "HEAD now followes $chain" >&2
else
    res=$(sib rev-parse "$chain" 2>/dev/null) || die "$chain is invalid"
    echo "switch to $chain ($(sib git rev-parse --short $res)) from $(sib git rev-parse --short HEAD)" >&2
    sib update-ref -m "switch to $chain" --no-deref HEAD $res
fi
